name: Commands processor

on:
  issue_comment:
    types: [created]

jobs:
  process:
    name: Process command
    if: ${{ github.event.issue.pull_request && endsWith(github.repository, '-private') != true && startsWith(github.event.comment.body, '@client-engineering-bot ') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout release actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Process changelog entries
        uses: ./.github/.release/actions/actions/commands
        with:
          token: ${{ secrets.GH_TOKEN }}
          listener: client-engineering-bot
          jira-api-key: ${{ secrets.JIRA_API_KEY }}
